### ISSUE TITLE
Criar políticas de repositório

### ISSUE THREAD

**Issue by lucasfcm9** [deeplearningunb/VaiDarLike#1]
## 2. Descrição da *Issue*
Criação do documento inicial das políticas de repositório. Nesse documento irá conter as políticas que devem ser seguidas para um usuário que queira contribuir com o projeto. Nele irá conter o documento de *branches*, *commits*, *issues* e *pull requests*. 

### 2.1 Tasks:

- [x] Criar template de *branches*;
- [x] Criar template de *commits*;
- [x] Criar template de *issues*;
- [x] Criar template de *pull requests*.

### 2.2 Critérios de Aceitação

- [x] Validação com todos os integrantes do grupo;
- [x] Templates prontos.

**Comment by lucasfcm9** [comment]
<img width="461" alt="logo" src="https://user-images.githubusercontent.com/40740008/69905393-99382280-1391-11ea-9b94-4be24f0517e8.png">

**Comment by lucasfcm9** [comment]
![tenor](https://user-images.githubusercontent.com/40740008/69905506-3051aa00-1393-11ea-92f9-8d629fc16e77.gif)
