### ISSUE TITLE
Análise exploratória dos dados

### ISSUE THREAD

**Issue by lucasfcm9** [deeplearningunb/VaiDarLike#13]
## 2. Descrição da *Issue*
Fazer a análise exploratória dos dados que consiste em interpretar e validar dados do *dataset* utilizado.

### 2.1 Tasks:

- [ ] Realizar a análise exploratória dos dados.

### 2.2 Critérios de Aceitação

- [ ] A análise exploratória estar coerente;
- [ ] Todos os dados devem estar interpretados;
- [ ] Validar com os integrantes do grupo.
