### ISSUE TITLE
Avaliação dos resultados de forma visual

### ISSUE THREAD

**Issue by lucasfcm9** [deeplearningunb/VaiDarLike#17]
## 2. Descrição da *Issue*
Deve ser possível ver a avaliação dos resultados de forma visual. Todos os gráficos e prints gerados devem estar de acordo com os objetivos do projeto e bem claros. 

### 2.1 Tasks:
- [ ] Gerar os gráficos resultantes;
- [ ] Mostrar a porcentagem de sucesso.

### 2.2 Critérios de Aceitação
- [ ] Deve ser possível visualizar todos os gráficos gerados;
