### ISSUE TITLE
Desenvolver algoritmo para Dataset

### ISSUE THREAD

**Issue by guilherme-mendes** [deeplearningunb/VaiDarLike#3]
## 2. Descrição da *Issue*
Desenvolver o algoritmo para o DataSet. Deve-se escalar todos os dados.

### 2.1 Tasks:

- [ ] Escalar os dados do DataSet;
- [ ] Desenvolver o algoritmo.

### 2.2 Critérios de Aceitação

- [ ] Os dados devem estar todos escalados;
- [ ] O algoritmo tem que estar funcionando perfeitamente.

**Comment by caiovfernandes** [comment]
# Opções de Dataset's 
## 1
[Trending YouTube Video Statistics](https://www.kaggle.com/datasnaek/youtube-new)

## 2
[YouTube Trending Video Statistics with Subscriber](https://www.kaggle.com/sgonkaggle/youtube-trend-with-subscriber)

## Descrição

Devemos definir um algoritmo de acordo com o **dataset** escolhido, criando uma relação de que maneira cada item irá impactar no sucesso ou não de um vídeo.

**Comment by caiovfernandes** [comment]
## Reunião com os integrantes via hangouts dia: _26/11/2019_

Definimos que o **Dataset** utilizado será o [Trending YouTube Video Statistics](https://www.kaggle.com/datasnaek/youtube-new). Tal decisão foi tomada pois este dataset possui a quantidade de _subscribers_ dos canais de cada vídeo. Isso nos dá a possibilidade de tratar o dataset de maneira a  melhorar a precisão e assertividade de nossa _Rede Neural_.

Inicialmente trataremos o **dataset** de modo a trazer uma variável dependente para cada registro por meio da média da coluna de _views_. Para cada registro que possuir este valor em nível de exigência superior à média, sua variável dependente será definida como **1**, caso contrário, **0**.
