### ISSUE TITLE
Definir Rede Neural

### ISSUE THREAD

**Issue by guilherme-mendes** [deeplearningunb/VaiDarLike#4]
## 2. Descrição da *Issue*
Definir qual rede neural será mais adequada para o projeto.

### 2.1 Tasks:

- [ ] Definição concreta da rede neural a ser utilizada;

### 2.2 Critérios de Aceitação

- [ ] Aprovação dos integrantes do grupo;
- [ ] A rede neural deve ser a mais adequada para o projeto.
