### ISSUE TITLE
Configurar ambiente de desenvolvimento

### ISSUE THREAD

**Issue by guilherme-mendes** [deeplearningunb/VaiDarLike#5]
## 2. Descrição da *Issue*
Configuração inicial do ambiente de desenvolvimento do projeto. Será utilizado o Docker para o ambiente de desenvolvimento.

### 2.1 Tasks:

- [ ] Configurar o Docker;
- [ ] Tudo deve estar funcionando perfeitamente.

### 2.2 Critérios de Aceitação

- [ ] Configuração correta do Docker.
- [ ] Todos os integrantes conseguirem utilizar o ambiente.
