### ISSUE TITLE
Cronograma 

### ISSUE THREAD

**Issue by guilherme-mendes** [deeplearningunb/VaiDarLike#7]
## 2. Descrição da *Issue*

Definição de todas as atividades no prazo delimitado para a entrega do projeto.

### 2.1 Tasks:

- [ ] Criar o cronograma e atribuir cada atividade aos integrantes do grupo.

### 2.2 Critérios de Aceitação

- [ ] Cronograma coerente e coeso;
- [ ] Aprovação dos integrantes do grupo.

**Comment by guilherme-mendes** [comment]
### **Cronograma v1.0**
![Copy of RoadMap - IHC](https://user-images.githubusercontent.com/37874689/69681929-71de0e80-108e-11ea-8778-1aaa1a424e6f.jpg)
