### ISSUE TITLE
Riscos para o projeto

### ISSUE THREAD

**Issue by guilherme-mendes** [deeplearningunb/VaiDarLike#8]
## 2. Descrição da *Issue*
Definição de todos os riscos para o projeto e para os membros do grupo.

### 2.1 Tasks:

- [x] Definir todos os riscos para os integrantes do grupo;
- [x] Definir todos os riscos para o projeto.

### 2.2 Critérios de Aceitação

- [x] Validação com todos os membros do grupo;
- [x] Riscos aceitáveis.

**Comment by guilherme-mendes** [comment]
* Verificar se o Dataset está de acordo e não depreciado;
* Viés do modelo;
* Qualidade dos dados;
* Hiperparâmetros;
* Falta de variabilidade do modelo;
* Interpretação de saída.
