### ISSUE TITLE
Definições do Produto

### ISSUE THREAD

**Issue by guilherme-mendes** [deeplearningunb/VaiDarLike#9]
## 2. Descrição da *Issue*
Definir todas as tarefas relacionadas ao produto.

### 2.1 Tasks:

- [ ] Definir todos os objetivos;
- [ ] Definir todas as metas do projeto;
- [ ] Definir todas as tarefas a serem realizadas;
- [ ] Definir qual é o problema;
- [ ] Definir os stekeholders do projeto;
- [ ] Definir a solução para o problema.

### 2.2 Critérios de Aceitação

- [ ] Aprovação dos integrantes do grupo.
- [ ] Definição concreta e clara de todas as tarefas.

**Comment by caiovfernandes** [comment]
## - Definições Iniciais:
### - Objetivos

Desenvolver um software para analisar informações referentes a um futura publicação no youtube, passado tais dados por um rede neural, checando quais são as probabilidades de tal publicação obter sucesso.

### - Metas

→ Prever probabilidade de sucesso de um vídeo;
→ Interface minimalista para execução do algoritmo;

→ 

### - Tarefas

[Desenvolver algoritmo para Dataset](https://www.notion.so/968adc14353b42bea09eaf39ace168ea)

[Definir Rede Neural](https://www.notion.so/d4294c2c35294274bdb62e5d184d49d7)

[Adicionar Docker ](https://www.notion.so/4efd9f153b8747138c4b73c24b165ae2)

[Repositório](https://www.notion.so/e68b5a099aa247c3ba2525d8c4cf11ca)

[Escolher Nome definitivo](https://www.notion.so/079d815aeb1f4afab2366a7c9aa968e0)

### - Qual é o problema?

 → Todo criador de conteúdo, ao publicar seu vídeo, não tem nenhum recurso para se seu vídeo vai viralizar ou não.

→ Falta de uma ferramenta que posso auxiliar criadores de conteúdo do Youtube a desenvolverem um estrutura para a postagem de seus vídeos, como:

- Título
- Descrição
- Tags

### - Quem são os stakeholders

→ Criadores de conteúdo para o youtube.

→ Audiência do youtube.

### - Qual é a solução proposta

→ Desenvolver uma ferramenta utilizando técnicas de Deep Learning. A partir de um **dataset** com informações de vídeos em alta, tendências e vídeos famosos, utilizaremos uma rede neural para processar esses dados e, de acordo com as entradas do usuário (Título, descrição, tags...) retornaremos informações sobre a chance do vídeo obter **sucesso**.
